### ISSUE TITLE
The authenticate.ex plug has a placeholder project name

### ISSUE THREAD

**Issue by nickjj** [zanderxyz/veil#1]
After running `mix veil.add` a bunch of folders and files were created as expected.

Inside most of those files, your task correctly changed `PhoenixExampleWeb` to my real project's name.

But `plugs/veil/authenticate.ex` on line 15 reads `Phoenix.Controller.redirect(conn, to: PhoenixExampleWeb.Router.Helpers.user_path(conn, :new))`.

I would have expected `PhoenixExampleWeb` to become my project name like the others automatically?

**Comment by zanderxyz** [comment]
Well spotted, you are correct. I've fixed this and uploaded 0.1.1, but it'll be easiest for you if you just change that occurrence yourself. I just searched and can't see any other placeholders (aside from one in a doc tag).

Thanks for raising this.

**Comment by nickjj** [comment]
No problem, yeah I just installed the package 5min ago and noticed my app started crashing from that curiously named project. I have fixed it on my end here.
