### ISSUE TITLE
BUG : protocol Enumerable not implemented

### ISSUE THREAD

**Issue by jean-smaug** [zanderxyz/veil#10]
Hi, i'm trying veil, the `no-html` version 

Got this error : 

```elixir
Protocol.UndefinedError at POST /veil/users
protocol Enumerable not implemented for "QBDTRBWJX7AXK3L4EER7PVJHXLEUD4LYTGZKDHDGJNKTKHSRX4GQ====". This protocol is implemented for: DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Postgrex.Stream, Range, Stream
```

Any idea ? 

Thanks

**Comment by zanderxyz** [comment]
Strange, let me check - do you have a line number for the code causing the error?

**Comment by jean-smaug** [comment]
Ligne 62 of the `veil.ex`

```elixir
defp new_session_url(conn, unique_id) do
    cur_uri = Phoenix.Controller.endpoint_module(conn).struct_url()
    cur_path = AppWeb.Router.Helpers.session_path(conn, :create, unique_id)
    AppWeb.Router.Helpers.url(cur_uri) <> cur_path
end
```

**Comment by zanderxyz** [comment]
I've fixed this - there's a new version up now. Things I changed:

1. Removed `get("/sessions/new/:request_id", SessionController, :create)` from the Router.
2. Changed `cur_path = TestWeb.Router.Helpers.session_path(conn, :create, unique_id)` to `cur_path = TestWeb.Router.Helpers.session_path(conn, :create, [request_id: unique_id])`

Please let me know if that works.

**Comment by jean-smaug** [comment]
No sorry, still got the same error

**Comment by zanderxyz** [comment]
Did you make the change to `cur_path = TestWeb.Router.Helpers.session_path(conn, :create, [request_id: unique_id])`? The error was happening because `unique_id` is a string rather than a list. But if you replace it with `[request_id: unique_id]` then it's a list and therefore implements the behaviour Enumerable. That will then generate the link correctly.

**Comment by jean-smaug** [comment]
Didn't understood that i need to make change, i thought that you were explaining what you've done ^^
OK for me it work great.
