### ISSUE TITLE
Is there a way to trigger a cache reload?

### ISSUE THREAD

**Issue by AndreasBraun2015** [zanderxyz/veil#18]
If I change something in the user, the cache still shows the old value. Is there a simple way to trigger a cache reload?

Many thanks for any help!

Best
Andreas

**Comment by zanderxyz** [comment]
Hi!

`Cachex.clear(:veil_users)` will clear the cache, but that is probably not what you want to do, as it will clear ALL the users. `Cache.del(:veil_users, USER_ID)` will clear a specific user for a given USER_ID.

Are you updating the User using the `YourApp.Veil.update_user/2` function? If you do, it should change the cache after the update to refer to the updated user.

Thanks
Zander

**Comment by zanderxyz** [comment]
That should read `Cachex.del(:veil_users, USER_ID)`

**Comment by AndreasBraun2015** [comment]
Perfect, many thanks for your help!
