### ISSUE TITLE
no function clause matching in Veil.verify/2

### ISSUE THREAD

**Issue by thantez** [zanderxyz/veil#24]
Hi.
I followed veil's official instruction an [this](https://elixircasts.io/passwordless-authentication-with-veil) to adding it in my project but for verification section it throws this error
`no function clause matching in Veil.verify/2`
an I tried create a new phoenix project for testing veil and I do it without any additional work! but I gave this error another time
so this is phoenix error page details:
`
%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, before_send: [#Function<0.41104819/1 in Plug.CSRFProtection.call/2>, #Function<2.64052486/1 in Phoenix.Controller.fetch_flash/2>, #Function<0.54074652/1 in Plug.Session.before_send/2>, #Function<0.110189767/1 in Plug.Telemetry.call/2>, #Function<0.126136900/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>], body_params: %{}, cookies: %{"_project_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYMDZ5NktPU0l6NUxFRGdVX0J1TmxuZzd1.Ka1I86vHSWu3oi2ZW9mvUO1KaLzwsuwKqp4l6pQcDOc", "session_unique_id" => "OTHCZF3R6PCBTTKTKOKQOSKQJPCXHMHCI53TUQVLP5BUIJ42GF7Q===="}, halted: false, host: "localhost", method: "GET", owner: #PID<0.32758.0>, params: %{"request_id" => "56VOVSQX4TCBUHPI45GVWOTWVKXUVRPB4QPQ5OMPLXYMMUKXUIZQ===="}, path_info: ["veil", "sessions", "new", "56VOVSQX4TCBUHPI45GVWOTWVKXUVRPB4QPQ5OMPLXYMMUKXUIZQ%3D%3D%3D%3D"], path_params: %{"request_id" => "56VOVSQX4TCBUHPI45GVWOTWVKXUVRPB4QPQ5OMPLXYMMUKXUIZQ===="}, port: 4000, private: %{ProjectWeb.Router => {[], %{}}, :phoenix_endpoint => ProjectWeb.Endpoint, :phoenix_flash => %{}, :phoenix_format => "html", :phoenix_router => ProjectWeb.Router, :plug_session => %{"_csrf_token" => "06y6KOSIz5LEDgU_BuNlng7u"}, :plug_session_fetch => :done}, query_params: %{}, query_string: "", remote_ip: {127, 0, 0, 1}, req_cookies: %{"_project_key" => "SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYMDZ5NktPU0l6NUxFRGdVX0J1TmxuZzd1.Ka1I86vHSWu3oi2ZW9mvUO1KaLzwsuwKqp4l6pQcDOc", "session_unique_id" => "OTHCZF3R6PCBTTKTKOKQOSKQJPCXHMHCI53TUQVLP5BUIJ42GF7Q===="}, req_headers: [{"accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.9"}, {"connection", "keep-alive"}, {"cookie", "_project_key=SFMyNTY.g3QAAAABbQAAAAtfY3NyZl90b2tlbm0AAAAYMDZ5NktPU0l6NUxFRGdVX0J1TmxuZzd1.Ka1I86vHSWu3oi2ZW9mvUO1KaLzwsuwKqp4l6pQcDOc; session_unique_id=OTHCZF3R6PCBTTKTKOKQOSKQJPCXHMHCI53TUQVLP5BUIJ42GF7Q===="}, {"host", "localhost:4000"}, {"sec-fetch-mode", "navigate"}, {"sec-fetch-site", "cross-site"}, {"sec-fetch-user", "?1"}, {"upgrade-insecure-requests", "1"}, {"user-agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36"}], request_path: "/veil/sessions/new/56VOVSQX4TCBUHPI45GVWOTWVKXUVRPB4QPQ5OMPLXYMMUKXUIZQ%3D%3D%3D%3D", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "Fbl--3GwlqVY6UwAAAYi"}, {"x-frame-options", "SAMEORIGIN"}, {"x-xss-protection", "1; mode=block"}, {"x-content-type-options", "nosniff"}, {"x-download-options", "noopen"}, {"x-permitted-cross-domain-policies", "none"}, {"cross-origin-window-policy", "deny"}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}
{:ok, %Project.Veil.Session{__meta__: #Ecto.Schema.Metadata<:loaded, "veil_sessions">, id: 3, inserted_at: ~N[2019-08-10 07:25:18], ip_address: "127.0.0.1", phoenix_token: "SFMyNTY.g3QAAAACZAAEZGF0YWECZAAGc2lnbmVkbgYAkddqemwB.PV8Kcnq8qhFBsoyv2Cjuq68O4Dz7TSw9-HEmtagJKkc", unique_id: "OTHCZF3R6PCBTTKTKOKQOSKQJPCXHMHCI53TUQVLP5BUIJ42GF7Q====", updated_at: ~N[2019-08-10 07:25:18], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 2}}
`

![image](https://user-images.githubusercontent.com/33148504/62819169-f308a880-bb66-11e9-9700-68617da62c66.png)
![image](https://user-images.githubusercontent.com/33148504/62819305-90b0a780-bb68-11e9-8a97-7bed807a61e6.png)

what should I do?
thanks

**Comment by seanwash** [comment]
@thantez I just ran into this, I think something changed with `Veil.get_session/1` in an update. Here's a quick workaround:

Open `Veil.UserId` and change line 14 from `{:ok, session} <- Veil.get_session(session_unique_id)` to `{:ok, {:ok, session}} <- Veil.get_session(session_unique_id)`.

In looking closer at the error message, I noticed that the 2nd arg is a tuple instead of a `%Rodinia.Veil.Session{}` or `%Rodinia.Veil.Request{}` struct.

**Comment by thantez** [comment]
> @thantez I just ran into this, I think something changed with `Veil.get_session/1` in an update. Here's a quick workaround:
> 
> Open `Veil.UserId` and change line 14 from `{:ok, session} <- Veil.get_session(session_unique_id)` to `{:ok, {:ok, session}} <- Veil.get_session(session_unique_id)`.
> 
> In looking closer at the error message, I noticed that the 2nd arg is a tuple instead of a `%Rodinia.Veil.Session{}` or `%Rodinia.Veil.Request{}` struct.

thanks. worked for me.
